grafana:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.bozyel.work

  persistence:
    enabled: false

  additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        isDefault: false

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true