apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: online-boutique
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
      targetRevision: main
      path: helm-chart
      helm:
          valueFiles:
            - $values/workloads/online-boutique/values.yaml

    - repoURL: git@github.com:mehmetbozyel/homelab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true